spring:
  datasource:
    username: root
    password: DB_PASSWORD
    url: jdbc:mysql://${DB_HOST:localhost}:{DB_PORT:3306}/${DB_NAME:movies}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format-sql: true

project:
  poster: posters/

base:
  url: http://localhost:8080

