spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/movies
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format-sql: true

project:
  poster: poster/



mail:
  host: smtp.gmail.com
  port: 587
  username: "ujjwal9019@gmail.com"
  password: "knyc ykyr zhsv wsoa"
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true



base:
  url: http://localhost:8080/

